kafka:
  consumer:
    stream: misc.ssl
    topic:
      - misc.ssl.validation
    group-id: sojourner-misc-dumper
    bootstrap-servers:
      slc:
        - rhs-jyrvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-jyrvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-jyrvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-jyrvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-jyrvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
      lvs:
        - rhs-pyrvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-pyrvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-pyrvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-pyrvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-pyrvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
      rno:
        - rhs-dyrvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-dyrvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-dyrvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-dyrvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-dyrvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
    max-poll-records: 3000
    # 16MB, default value is 50MB
    fetch-max-bytes: 16777216
    # 128KB, default value is 64KB
    receive-buffer: 131072
    fetch-max-wait-ms: 100
    # 4MB, default value is 1MB
    max-partitions-fetch-bytes: 4194304
    auto-offset-reset: latest
    partition-discovery-interval-ms: 60000
flink:
  app:
    name: Sojourner New Feature Onboarding HDFS Load Pipeline
    parallelism:
      source: 20
      process: 20
      sink:
        hdfs:
          new_feature_onboarding_watermark: 20
          new_feature_onboarding: 20
    operator-name:
      source: consumer operator
      process: process operator
      sink: sink operator
    uid:
      source: consumer-operator
      process: process-operator
      sink: sink-operator
    slot-sharing-group:
      source: consumer-group
      process: process-group
      sink: sink-group
    metric:
      watermark-process-progress: new-feature-onboarding-watermark-delay-time
    checkpoint:
      data-dir: /opt/sojourner-ubd/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1
      tolerate-failure-number: 3
    source:
      dc: rno,lvs,slc
    sink:
      eventtype: new_feature_onboarding
      watermark: new_feature_onboarding_watermark
hdfs:
  dump:
    path:
      new_feature_onboarding: hdfs://apollo-router/sys/soj/ubd/misc_test/
      new_feature_onboarding_watermark: hdfs://apollo-router/sys/soj/ubd/misc_test_watermark/