kafka:
  consumer:
    stream: misc.ssl
    topic: misc.ssl.validation
    group-id: sojourner-misc-dumper
    bootstrap-servers:
      rno:
        - rhs-jyrvkiaa-kfk-slc-1.rheos-streaming-prod.svc.23.tess.io:9092
        - rhs-jyrvkiaa-kfk-slc-2.rheos-streaming-prod.svc.23.tess.io:9092
        - rhs-jyrvkiaa-kfk-slc-3.rheos-streaming-prod.svc.23.tess.io:9092
        - rhs-jyrvkiaa-kfk-slc-4.rheos-streaming-prod.svc.23.tess.io:9092
        - rhs-jyrvkiaa-kfk-slc-5.rheos-streaming-prod.svc.23.tess.io:9092

flink:
  app:
    name: Sojourner Misc HDFS Load Pipeline
    parallelism:
      source: 20
      sink:
        hdfs: 20

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/misc_test/
    class-name: com.ebay.sojourner.common.model.MiscEvent