kafka:
  consumer:
    stream: behavior.pathfinder
    topic: behavior.pathfinder.events.guidsubscription
    group-id: sojourner-skew-guid-dumper
    bootstrap-servers:
      slc:
        - rhs-mwsvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-mwsvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-mwsvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-mwsvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-mwsvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
      lvs:
        - rhs-swsvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-swsvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-swsvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-swsvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-swsvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
      rno:
        - rhs-glrvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-glrvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-glrvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-glrvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-glrvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092

    max-poll-records: 3000
    # 16MB, default value is 50MB
    fetch-max-bytes: 16777216
    # 128KB, default value is 64KB
    receive-buffer: 131072
    fetch-max-wait-ms: 100
    # 4MB, default value is 1MB
    max-partitions-fetch-bytes: 4194304
    auto-offset-reset: latest

flink:
  app:
    name: Sojourner skew guid HDFS Load Pipeline
    parallelism:
      source: 1
      sink:
        hdfs: 1
    checkpoint:
      data-dir: /opt/sojourner-ubd/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1
      tolerate-failure-number: 3

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production

hdfs:
  dump:
    path: hdfs://apollo-router/sys/soj/ubd/skew-guid-prod/
    class-name: model.SkewGuid