kafka:
  consumer:
    stream: behavior.pathfinder
    topic: behavior.total.new.surfaceevent
    group-id: uni-sess-dumper-poc
    bootstrap-servers:
      rno:
        - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092

    max-poll-records: 3000
    # 16MB, default value is 50MB
    fetch-max-bytes: 16777216
    # 128KB, default value is 64KB
    receive-buffer: 131072
    fetch-max-wait-ms: 100
    # 4MB, default value is 1MB
    max-partitions-fetch-bytes: 4194304
    auto-offset-reset: latest

flink:
  app:
    name: Unified Sessionization AutoTrack HDFS Load Pipeline
    parallelism:
      source: 10
      sink:
        hdfs: 10
    checkpoint:
      data-dir: /opt/sojourner-ubd/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1
      tolerate-failure-number: 3

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production

hdfs:
  dump:
    path: hdfs://apollo-router/sys/soj/ubd/uni-sess-autotrack/
    class-name: model.AutoTrackEvent