kafka:
  consumer:
    stream: misc.ssl
    topic: misc.ssl.validation
    group-id: sojourner-misc-dumper
    bootstrap-servers:
      slc:
        - rhs-jyrvkiaa-kfk-slc-1.rheos-streaming-prod.svc.23.tess.io:9092
        - rhs-jyrvkiaa-kfk-slc-2.rheos-streaming-prod.svc.23.tess.io:9092
        - rhs-jyrvkiaa-kfk-slc-3.rheos-streaming-prod.svc.23.tess.io:9092
        - rhs-jyrvkiaa-kfk-slc-4.rheos-streaming-prod.svc.23.tess.io:9092
        - rhs-jyrvkiaa-kfk-slc-5.rheos-streaming-prod.svc.23.tess.io:9092
      lvs:
        - rhs-pyrvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.27.tess.io:9092
        - rhs-pyrvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.27.tess.io:9092
        - rhs-pyrvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.27.tess.io:9092
        - rhs-pyrvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.27.tess.io:9092
        - rhs-pyrvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.27.tess.io:9092
      rno:
        - rhs-dyrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-dyrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-dyrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-dyrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-dyrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092

    max-poll-records: 3000
    # 16MB, default value is 50MB
    fetch-max-bytes: 16777216
    # 128KB, default value is 64KB
    receive-buffer: 131072
    fetch-max-wait-ms: 100
    # 4MB, default value is 1MB
    max-partitions-fetch-bytes: 4194304
    auto-offset-reset: latest

flink:
  app:
    name: Sojourner Misc HDFS Load Pipeline
    parallelism:
      source: 20
      sink:
        hdfs: 20
    checkpoint:
      data-dir: /opt/sojourner-ubd/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1
      tolerate-failure-number: 3

rheos:
#  registry-url: https://rheos-services.stratus.ebay.com
  registry-url: https://rheos-services.qa.ebay.com
  client:
    id:
    iaf:
      secret:
      env: production

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/misc_test/
    class-name: model.MiscEvent