kafka:
  consumer:
    max-poll-records: 3000
    # 16MB, default value is 50MB
    fetch-max-bytes: 16777216
    # 128KB, default value is 64KB
    receive-buffer: 131072
    fetch-max-wait-ms: 100
    # 4MB, default value is 1MB
    max-partitions-fetch-bytes: 4194304
    auto-offset-reset: latest

flink:
  app:
    name: Sojourner Non Bot Event HDFS Load Pipeline
    parallelism:
      source: 150
      sink:
        kafka: 100
        hdfs: 150
    checkpoint:
      data-dir: /opt/sojourner-ubd/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1
      tolerate-failure-number: 3

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    id:
    iaf:
      secret: 
      env: production