kafka:
  consumer:
    topic:
      - behavior.akamailog.event
    group-id: akamai-dumper
    bootstrap-servers:
      lvs:
        - rhs-ejbwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-ejbwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-ejbwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-ejbwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
    max-poll-records: 3000
    # 16MB, default value is 50MB
    fetch-max-bytes: 16777216
    # 128KB, default value is 64KB
    receive-buffer: 131072
    fetch-max-wait-ms: 100
    # 4MB, default value is 1MB
    max-partitions-fetch-bytes: 4194304
    auto-offset-reset: latest
    # 60s, default is disabled
    partition-discovery-interval-ms: 60000

flink:
  app:
    name: Akamai Log dumper Pipeline
    parallelism:
      source: 20
      sink:
        hdfs:
          akamai_event: 15
          akamai_watermark: 15
    operator-name:
      assgin-watermark: Akamai Log Watermark Assign
      extract-watermark: Akamai Log Timestamp Extract
      sink:
        event: Akamai Log Dumper Sink
        watermark: Akamai Log Watermark Sink
    uid:
      assgin-watermark: akamai-log-watermak-assign
      extract-watermark: akamai-log-timestamp-extract
      sink:
        event: akamai-log-dumper-sink
        watermark: akamai-log-watermark-sink
    metric:
      watermark-process-progress: sojourner-ubd-akamai-log-watermark-delay-time
    checkpoint:
      data-dir: /opt/flink/akamailog/dumper/checkpoint

hdfs:
  dump:
    path:
      akamai_event: hdfs://apollo-router/sys/edw/working/ubi/ubi_w/soj/stg_ubi_akamai_dump_w
      akamai_watermark: hdfs://apollo-router/sys/edw/working/ubi/ubi_w/soj/stg_ubi_akamai_watermark_lkp

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production